### ISSUE TITLE
implement symbol renaming

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/nominal-binding-algebras#10]
So—One thing I'd like to get straight is how to lift renamings of symbols into terms. Here's the basics of how I'm thinking it works, but I'm not totally sure. Let `F` be the category of finite sets of symbols and their injective maps; let `S` be the (discrete) category of sorts; let `A` be the (discrete) category of arities; let `SCtx = F ↓ S`, the category of symbol contexts whose objects are assignments of sorts to symbols, and whose morphisms are symbol renamings that preserve sort.

- A renaming of symbols is an arrow `ψ : F[U, V]`

- Maps in the index category of the operator presheaf on `SCtx * A` are pairs of maps `<ψ : SCtx[Γ,Δ], id>`. Since `A` is discrete (i.e. only has identities), we really only need to consider the maps in that comma category.

- Maps in `SCtx` are really just maps in `F` subject to some laws.

Therefore, we should be able to apply renamings `ψ` to apply on operators, by lifting `<ψ, id>` into the presheaf. Then, we can just apply this recursively, being careful at symbol binding sites.

@freebroccolo Does that sound plausible?

**Comment by freebroccolo** [comment]
Ah, sorry I forgot to reply to this, but yes, I think that sounds reasonable.

**Comment by jonsterling** [comment]
@freebroccolo Thanks, no worries! I've committed a preliminary attempt at this, but just realized I forgot to take `psi` to `<psi, id>`.
